// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgeXEwMRozxa2F423t2WRScL5vTN3zQso',
    appId: '1:1056977117003:android:e676914b05ecb77ee2d2ce',
    messagingSenderId: '1056977117003',
    projectId: 'nursingplus-eg',
    storageBucket: 'nursingplus-eg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjE17tlo0HAgEh8jcH5gM_h-z-Bdb7URU',
    appId: '1:1056977117003:ios:e02cb9d4b75e0876e2d2ce',
    messagingSenderId: '1056977117003',
    projectId: 'nursingplus-eg',
    storageBucket: 'nursingplus-eg.firebasestorage.app',
    androidClientId: '1056977117003-49ku1h7uevhn8kcmgmusbtt07h0v7is7.apps.googleusercontent.com',
    iosClientId: '1056977117003-mt37t12og11ukho79i1r5n6a1qduaod3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nursingplus',
  );

}